### PR TITLE
Use the full display name of projects in notifications

### LINKED ISSUE #31: Project name is not very clear in notifications for multi-branch pipeline projects
When I use the `ZulipNotifier` in a [multi-branch pipeline](https://plugins.jenkins.io/workflow-multibranch/) project, I get notifications that look like this:

> Project: production : Build: #1: SUCCESS 

> Project: staging : Build: #3: SUCCESS

The "project name" in these examples is in fact the branch name. That's because, for multi-branch pipeline projects, one sub-project is created for each branch, and this sub-project has the same name as the branch.

This notification message is not very clear, since it doesn't allow to identify the failing Jenkins job.

Ideally we should make the message clearer?

### Version report

Jenkins and plugins versions report:

```
Jenkins: 2.289.2
OS: Linux - 4.18.0-305.7.1.el8_4.x86_64
---
jaxb:2.3.0.1
pipeline-milestone-step:1.3.2
cloudbees-folder:6.15
branch-api:2.6.5
jdk-tool:1.5
script-security:1.77
docker-commons:1.17
structs:1.23
momentjs:1.1.1
workflow-step-api:2.24
scm-api:2.6.4
docker-workflow:1.26
workflow-api:2.46
junit:1.51
command-launcher:1.6
pipeline-stage-view:2.19
bouncycastle-api:2.20
gradle:1.37.1
antisamy-markup-formatter:2.1
token-macro:2.15
build-timeout:1.20
credentials:2.5
pipeline-build-step:2.13
plain-credentials:1.7
ssh-credentials:1.19
pipeline-model-api:1.8.5
credentials-binding:1.27
workflow-support:3.8
durable-task:1.38
workflow-durable-task-step:2.39
matrix-project:1.19
jsch:0.1.55.2
resource-disposer:0.16
github-api:1.123
ws-cleanup:0.39
ace-editor:1.1
jquery-detached:1.2.1
git-client:3.8.0
workflow-scm-step:2.13
git:4.7.2
workflow-cps:2.93
workflow-job:2.41
github:1.33.1
apache-httpcomponents-client-4-api:4.5.13-1.0
display-url-api:2.3.5
mailer:1.34
git-server:1.10
workflow-basic-steps:2.23
jackson2-api:2.12.3
workflow-cps-global-lib:2.21
pipeline-input-step:2.12
pipeline-stage-step:2.5
pipeline-graph-analysis:1.11
pipeline-rest-api:2.19
handlebars:3.0.8
pipeline-model-extensions:1.8.5
blueocean-git-pipeline:1.24.7
workflow-multibranch:2.26
blueocean-jwt:1.24.7
authentication-tokens:1.4
h2-api:1.4.199
pipeline-stage-tags-metadata:1.8.5
favorite:2.3.3
pipeline-model-definition:1.8.5
lockable-resources:2.11
workflow-aggregator:2.6
github-branch-source:2.11.1
pipeline-github-lib:1.0
matrix-auth:2.6.7
sse-gateway:1.24
email-ext:2.83
embeddable-build-status:2.0.3
blueocean-config:1.24.7
config-file-provider:3.8.1
throttle-concurrents:2.3
blueocean-events:1.24.7
github-oauth:0.33
windows-slaves:1.8
ant:1.11
ghprb:1.42.2
jquery:1.12.4-1
javadoc:1.6
pam-auth:1.6
ldap:2.7
external-monitor-job:1.7
pubsub-light:1.16
blueocean-pipeline-scm-api:1.24.7
htmlpublisher:1.25
node-iterator-api:1.5.0
variant:1.4
zulip:1.2.1
aws-java-sdk:1.11.995
blueocean-dashboard:1.24.7
aws-credentials:1.29
doclinks:0.6.1
ec2:1.62
blueocean-jira:1.24.7
authorize-project:1.4.0
ssh-agent:1.23
maven-plugin:3.12
envinject-api:1.7
audit-trail:3.8
jobConfigHistory:2.28.1
jira:3.5
simple-theme-plugin:0.7
PrioritySorter:4.0.0
blueocean-rest-impl:1.24.7
jenkins-design-language:1.24.7
blueocean-display-url:2.4.1
blueocean-core-js:1.24.7
blueocean-commons:1.24.7
blueocean-rest:1.24.7
blueocean-web:1.24.7
ssh-slaves:1.32.0
postbuildscript:3.0.0
conditional-buildstep:1.4.1
parameterized-trigger:2.41
database-mysql:1.4
run-condition:1.5
blueocean-autofavorite:1.2.4
database:1.9
trilead-api:1.0.13
pipeline-github:2.7
pipeline-utility-steps:2.8.0
notification:1.15
pipeline-maven:3.10.0
snakeyaml-api:1.29.1
greenballs:1.15.1
blueocean-pipeline-api-impl:1.24.7
blueocean-github-pipeline:1.24.7
blueocean-personalization:1.24.7
blueocean-i18n:1.24.7
envinject:2.4.0
mysql-api:8.0.16
openshift-client:1.0.35
plugin-util-api:2.4.0
jmh-report:0.9.0
toolenv:1.2
warnings-ng:9.4.0
caffeine-api:2.9.1-23.v51c4e2c879c8
bootstrap5-api:5.0.2-1
jquery3-api:3.6.0-2
analysis-model-api:10.2.5
font-awesome-api:5.15.3-4
popper2-api:2.5.4-3
data-tables-api:1.10.25-2
popper-api:1.16.1-2
sshd:3.0.4
jjwt-api:0.11.2-9.c8b45b8bb173
echarts-api:5.1.2-3
checks-api:1.7.2
okhttp-api:3.14.9
forensics-api:1.2.1
bootstrap4-api:4.6.0-3
```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
RHEL 8 on controller, Fedora 34 on agents.
```

### Reproduction steps

- Create a multi-branch pipeline project
- Set up Zulip notifications in that project
- Trigger a build and check out the notification

### Results

**Expected result:**

The notification should include the project name and branch, e.g.:

> Project: hibernate.org » production : Build: #1: SUCCESS 

**Actual result:**

The notification does not include the project name, only the branch name, e.g.:

> Project: production : Build: #1: SUCCESS

### PR DESCRIPTION
**Pull request by yrodiere**
Fixes #31.

Use the full display name of projects in notifications instead of the "relative" name.

I.e. a job named "TestJob" in a folder named "Folder" will be displayed as "Folder » TestJob" instead of just "TestJob".

More importantly, a job for branch "production" in a multi-branch pipeline project named "TestJob" will be displayed as "TestJob » production" instead of just "production".

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by yrodiere** [comment]
Hey @butchyyyy ; any chance to get this merged and released? Do I need to change anything?

**Comment by butchyyyy** [comment]
Hi, thank your for taking the time to contribute to the Jenkin's zulip-plugin. I'm sorry for the super late reply - as you probably figured out - I'm not actively maintaining this plugin anymore.

Couple comments regarding the change:
- Instead of using `getFullDisplayName()`, you could loop through build parents. The advantage being you would get separate url to branch project and the whole multi branch pipeline (similar to what we have now where there is a separate url for build and for branch project).
- To be consistent, you should probably also use the full project's name as topic name in case the notifier is not posting into a fixed one.

I assume that your use case is that your team maintains multiple multi branch pipelines and post them all into same stream + topic. I have a slight concern that people that have dedicated stream + topic for each multi branch pipeline will get additional verbosity that they don't need. Can you give introducing a configuration options for this a thought? It would default to what we have now with the option to display the full name instead.

**Comment by yrodiere** [comment]
@butchyyyy Thanks for the feedback. Here is an updated version adjusted according to your comments. I also made sure to update `ZulipSendStep`, which I had missed originally.

Does this look good? The tests seem to pass, but I'm not sure what I did about the configuration options ir right: I've never added a configuration option to a Jenkins plugin before.

File: src/main/java/jenkins/plugins/zulip/ZulipUtil.java [hunk 1]
```diff
@@ -73,4 +76,68 @@ public static String expandVariables(@Nonnull Run<?, ?> run, @Nonnull TaskListen
...
+     * Helper method to display a job, optionally with links.
+     *
+     * @param job          The job to display.
+     * @param globalConfig Zulip global configuration.
+     * @param fullJobPath  Whether to display the full path including the display name of parent items
+     *                     ({@code true}) or just this job's display name ({@code false}).
+     * @param displayLinks Whether to display links to the job and (if relevant) its parent items.
+     * @return A string representing the job.
+     */
+    public static String displayJob(Job<?, ?> job, DescriptorImpl globalConfig, boolean fullJobPath, boolean displayLinks) {
```
Comment (butchyyyy) [inline src/main/java/jenkins/plugins/zulip/ZulipUtil.java]: nit: Can you add tests for the new helper methods?

File: src/main/resources/jenkins/plugins/zulip/ZulipNotifier/global.jelly [hunk 2]
```diff
@@ -29,6 +29,15 @@
     <f:entry title="Default Topic Name" help="/plugin/zulip/help-globalConfig-topic.html">
         <f:textbox name="topic" value="${descriptor.getTopic()}" />
     </f:entry>
+    <f:entry title="Use full job path in default topic name" help="/plugin/zulip/help-globalConfig-fullJobPathAsDefaultTopic.html">
+        <f:checkbox name="fullJobPathAsDefaultTopic" checked="${descriptor.isFullJobPathAsDefaultTopic()}" />
+    </f:entry>
+    <f:entry title="Use full job path in notification message" help="/plugin/zulip/help-globalConfig-fullJobPathInMessage.html">
+        <f:checkbox name="fullJobPathInMessage" checked="${descriptor.isFullJobPathInMessage()}" />
+    </f:entry>
+    <f:entry title="Enable Smart Notification" help="/plugin/zulip/help-globalConfig-smartNotify.html">
```
Comment (butchyyyy) [inline src/main/resources/jenkins/plugins/zulip/ZulipNotifier/global.jelly:38]: Duplicates the smart notification settings.

**Review by butchyyyy — COMMENTED** [review]
This is awesome! Couple more comments (one might be the reason of integration test failure).

I'll work on my local set up to give this a quick test on my end and to be able to release this eventually. Please bear with me if this takes couple more days as I did not do anything Jenkins or Java related for over a year.

File: src/main/resources/jenkins/plugins/zulip/ZulipNotifier/global.jelly (hunk 2 above)
Comment (yrodiere) [reply src/main/resources/jenkins/plugins/zulip/ZulipNotifier/global.jelly:38]: Sorry, that was a copy/paste error. I'll remove it.

**Comment by yrodiere** [comment]
I addressed your comments. Thanks for the review, and thanks for your work on the release :)

If you haven't worked on this project or on Java projects for a while, this piece of information may be useful: this project apparently only compiles on Java 8. That shouldn't impact end-users, but if you're reinstalling everything, make sure you install JDK 8, not 11 or 17.

File: src/main/java/jenkins/plugins/zulip/DescriptorImpl.java [hunk 3]
```diff
@@ -94,6 +96,22 @@ public void setTopic(String topic) {
         this.topic = topic;
     }
 
+    public boolean isFullJobPathAsDefaultTopic() {
```
Comment (butchyyyy) [inline src/main/java/jenkins/plugins/zulip/DescriptorImpl.java:99]: You also need to add the new fields to the `configure` method:

```java
fullJobPathAsDefaultTopic = Boolean.TRUE.equals(json.get("fullJobPathAsDefaultTopic"));
fullJobPathInMessage = Boolean.TRUE.equals(json.get("fullJobPathInMessage"));
```

File: src/main/java/jenkins/plugins/zulip/ZulipUtil.java [hunk 4]
```diff
@@ -73,4 +76,69 @@ public static String expandVariables(@Nonnull Run<?, ?> run, @Nonnull TaskListen
...
+     * @param globalConfig Zulip global configuration.
+     * @param fullPath     Whether to display the full path including the display name of parent items
+     *                     ({@code true}) or just this object's display name ({@code false}).
+     * @param displayLinks Whether to display links to the object and (if relevant) its parent items.
+     */
+    private static void displayObject(StringBuilder builder, ModelObject object, String url, DescriptorImpl globalConfig,
+                                      boolean fullPath, boolean displayLinks) {
+        // The only common interface between Item and ItemGroup is ModelObject, which doesn't define getParent,
+        // so we need to resort to instanceof + cast to crawl up the item tree.
+        if (fullPath && object instanceof Item) {
```
Comment (butchyyyy) [inline src/main/java/jenkins/plugins/zulip/ZulipUtil.java:114]: Traversing all the way to the top will also print out the Jenkins instance itself which is something we most likely want to avoid.
image

One possibility is to add something like this to the beginning of the method:

```java
if (object instanceof jenkins.model.Jenkins) {
    return;
}
```

**Review by butchyyyy — COMMENTED** [review]
Got around to test this and found couple problems, once they are addressed this will be ready to merge and release.

**Comment by yrodiere** [comment]
Thanks, and sorry for not noticing that, I guess I should have spun up a Jenkins instance instead of trusting my tests blindly :/

I added two commits to fix the problems you reported.

**Review by butchyyyy — APPROVED** [review]

**Comment by butchyyyy** [comment]
Release 1.3.0 has been published to Jenkins artifactory and the new version should be available in update centre in under 24hours.
Thanks for being patient with this dragging for so long (was super busy at work GAing new product).

Let me know if you run into any issue.

**Comment by yrodiere** [comment]
I installed the update and it work. Thank you very much for the reviews and release!
